inherit_from: .rubocop_todo.yml

Metrics/ModuleLength:
  Exclude:
    - "**/*_spec.rb"

Metrics/BlockLength:
  Exclude:
    - "**/*_spec.rb"
    - "fusuma.gemspec"

Metrics/LineLength:
  Max: 100
  Exclude:
    - "fusuma.gemspec"
